### ISSUE TITLE
README does not explain ReactGotoDef as a function

### ISSUE THREAD

**Issue by Nimor111** [Ivo-Donchev/goto-definition-plugin-for-react#1]
Hey,

Great work on this plugin! Works amazing. :+1: 

Just a little issue I found in the [README](https://github.com/Ivo-Donchev/vim-react-goto-definition#usage):

The `ReactGotoDef` seems to be a function, not a command, so calling it directly from vim works with
```
:call ReactGotoDef()
```
And not with 
```
:ReactGotoDef
```

Regards,
Georgi

**Comment by Ivo-Donchev** [comment]
Hey, thank you !!! :panda_face: 
Just fixed that https://github.com/Ivo-Donchev/vim-react-goto-definition/commit/66f531693d44070020dc882c6e6f5e4cd350580f
